language: node_js

node_js:
  - 16

services:
  - docker

jobs:
  include:
    - stage: conventional_commit_check
      language: node_js
      node_js: 16
      install: skip
      before_script:
        - npm install -g @commitlint/cli @commitlint/config-conventional
      script:
        - commitlint --from=HEAD~1
      if: type = pull_request
    - stage: build
      install: skip
      before_script:
        - npm install -g @angular/cli
        - npm install
      script:
        - npm run build
      if: (branch = master) OR (branch = develop) OR (type = pull_request)
    - stage: test
      install: skip
      before_script:
        - npm install -g @angular/cli
        - npm install
      script:
        - ng test --browsers=ChromeNoSandboxHeadless --watch=false
      if: (branch = master) OR (branch = develop) OR (type = pull_request)
    - stage: artifact_deploy
      install: skip
      script:
        - npx semantic-release
      if: (branch = master and type != pull_request) OR (branch = develop and type != pull_request)
    - stage: docker_deploy
      install: skip
      before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      script:
        - docker build -t draganagrbic/devops_dislinkt_frontend_app:latest .
        - docker push draganagrbic/devops_dislinkt_frontend_app:latest
        - docker tag draganagrbic/devops_dislinkt_frontend_app:latest draganagrbic/devops_dislinkt_frontend_app:$(git describe --tags --abbrev=0 | cut -b 2-)
        - docker push draganagrbic/devops_dislinkt_frontend_app:$(git describe --tags --abbrev=0 | cut -b 2-)
      if: (branch = master and type != pull_request) OR (branch = develop and type != pull_request)
