services:
  loki:
    image: grafana/loki:2.0.0
    volumes:
      - ./loki.yml:/mnt/config/loki.yml
    command: -config.file=/mnt/config/loki.yml
    networks:
      - monitoring
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:8.5.3
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    ports:
      - 3000:3000

  renderer:
    image: grafana/grafana-image-renderer:3.4.2
    environment:
      ENABLE_METRICS: "true"
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:1.34
    networks:
      - monitoring
    ports:
      - 9000:16686

  prometheus:
    image: prom/prometheus:v2.35.0
    restart: on-failure
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/var/lib/prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:v1.1.2
    networks:
      - monitoring
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    ports:
      - 8080:8080


volumes:
  grafana:
  prometheus:

networks:
  monitoring:
    name: monitoring
