  global:
    scrape_interval:     15s
    evaluation_interval: 15s

  rule_files:
   - "rules/recording_rules.yml"

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'grafana'
      static_configs:
        - targets: ['grafana:3000']

    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: 'cAdvisor'
      static_configs:
        - targets: [ 'cadvisor:8080' ]

    - job_name: auth_service
      static_configs:
        - targets: ['auth_service:8000']

    - job_name: profile_service
      static_configs:
        - targets: ['profile_service:8001']

    - job_name: offer_service
      static_configs:
        - targets: ['offer_service:8002']

    - job_name: event_service
      static_configs:
        - targets: ['event_service:8003']

    - job_name: message_service
      static_configs:
        - targets: ['message_service:8012']

    - job_name: post_service
      static_configs:
        - targets: ['post_service:8010']
